### PR TITLE
Fix Gradle Up-To-Date check.

### LINKED ISSUE #21: Should only run when there are changes
The scalastyle plugin does not support incremental building. It should only run when there are changes since the last run.

### PR DESCRIPTION
**Pull request by wdschei**
This will definitely fix #21 and might also address #42 .

### CODE REVIEW

**Comment by wdschei** [comment]
This new layout makes it easy to support Scala v2.13 and v2.14 when they are released too.

**Comment by ngbinh** [comment]
Thanks, will release new version today

**Comment by wdschei** [comment]
Glad we could help out on this. We were finishing the cleanup of our build for [Repose](https://github.com/rackerlabs/repose) and this was the last task that was not honoring the new Gradle Up To Date checks. We will start consuming the new version as soon as it is cut.

We started maintaining the abandoned [gradle-jaxb-plugin](https://github.com/rackerlabs/gradle-jaxb-plugin) and converted a maven plugin over to Gradle for verifying our Asciidoctor docs before publishing that is called [gradle-linkchecker-plugin](https://github.com/rackerlabs/gradle-linkchecker-plugin).

If you need any help with #10 just let me know. It is pretty easy as long as you always use the latest [plugin-publish-plugin](https://plugins.gradle.org/plugin/com.gradle.plugin-publish). The instructions can be found [here](https://plugins.gradle.org/docs/publish-plugin).

We have also found [gradleTest](http://ysb33rorg.gitlab.io/gradleTest/) to be handy for confirming the plugins we maintain are compatible with older versions of Gradle.

Thanks for keeping this plugin alive.

**Comment by ngbinh** [comment]
@wdschei could you step up and help me maintain this plugin? I haven't been able to keep up with this.

Many thanks for the contribution.

**Comment by wdschei** [comment]
@ngbinh What kind of help are you needing?

**Pull request merged**
