### PR TITLE
Updated to gradle 3.0

### PR DESCRIPTION
**Pull request by hanny24**

### CODE REVIEW

**Comment by tzachz** [comment]
+1

**Comment by nathanalderson** [comment]
+1

I maintain a plugin for use internally at my company which applies a number of plugins, including this one. We currently can't migrate to gradle 3.x because this plugin causes an exception when being added to the project:

```
unit.TestScalaStyleSupport > testAddsScalaStylePlugin FAILED
    org.gradle.api.internal.plugins.PluginApplicationException: Failed to apply plugin [id 'scalaStyle']
        at unit.TestScalaStyleSupport.testAddsScalaStylePlugin(TestScalaStyleSupport.groovy:21)

        Caused by:
        org.gradle.api.GradleException: Could not generate a proxy class for class org.github.ngbinh.scalastyle.ScalaStyleTask.
            at unit.TestScalaStyleSupport.testAddsScalaStylePlugin(TestScalaStyleSupport.groovy:21)

            Caused by:
            java.lang.NoClassDefFoundError: org/gradle/api/internal/DynamicObject
                at unit.TestScalaStyleSupport.testAddsScalaStylePlugin(TestScalaStyleSupport.groovy:21)

                Caused by:
                java.lang.ClassNotFoundException: org.gradle.api.internal.DynamicObject
                    at unit.TestScalaStyleSupport.testAddsScalaStylePlugin(TestScalaStyleSupport.groovy:21)
```

**Comment by ngbinh** [comment]
thanks, sorry for the delay. Will publish shortly

**Comment by ngbinh** [comment]
published.

**Comment by hanny24** [comment]
great :+1:

**Pull request merged**
